development: 
  cloud_name: "onlinereview-development"
  api_key: <%= Rails.application.credentials[:cloudinary][:development][:api_key] %>
  api_secret: <%= Rails.application.credentials[:cloudinary][:development][:api_secret] %>
  secure: true

production:
  cloud_name: "onlinereview-production"
  api_key: <%= Rails.application.credentials[:cloudinary][:production][:api_key] %>
  api_secret: <%= Rails.application.credentials[:cloudinary][:production][:api_secret] %>
  secure: true
  