development: 
  publishable_key: <%= Rails.application.credentials[Rails.env.to_sym][:stripe][:publishable_key] %>
  secret_key: <%= Rails.application.credentials[Rails.env.to_sym][:stripe][:secret_key] %>
  webhooks: <%= Rails.application.credentials[Rails.env.to_sym][:stripe][:webhooks] %>
  secure: true

production:
  publishable_key: <%= Rails.application.credentials[Rails.env.to_sym][:stripe][:publishable_key] %>
  secret_key: <%= Rails.application.credentials[Rails.env.to_sym][:stripe][:secret_key] %>
  webhooks: <%= Rails.application.credentials[Rails.env.to_sym][:stripe][:webhooks] %>
  secure: true
